### ISSUE TITLE
ishodi ucenja i rjesene domace zadace

### ISSUE THREAD

**Issue by InCogNiTo124** [studosi-fer/STRUCE#1]
akademske godine gospodnje 2019./2020. studenti bivseg foruma su u veliki djeljeni Google doc file ukratko napisali sve ishode ucenja i rijesili domace zadace.

[Ishodi uceja](https://docs.google.com/document/d/10HPz5l8SXQmWg1_cS6Pl92Q25nungtGjsDeqLgxCf_s/edit#)
[Domace zadace](https://docs.google.com/document/d/1POm4KkLzv3M_R1Lf7m3nnvp-2MJ-JYHRMKRJNCprJwU/edit#)

Mozda ne bi bilo lose dodati ove poveznice ili mozda datoteke u repozitorij

**Comment by InCogNiTo124** [comment]
Otvaram issue zato jer nisam siguran u kojem bi obliku trebali biti dodani, kao obicni linkovi ili u neki posebni readme

**Comment by studosi-fer** [comment]
Pretpostavljam da je .docx format koji se može uređivati. Važno je samo da je neki neopskurni urediv format (iako će vjerojatno u konačnici to sve ići u latex/markdown.

**Comment by InCogNiTo124** [comment]
Mislim, moja ideja je bila da to ostane na tim linkovima, odnosno da u ovaj repo stavim samo linkove na to

**Comment by studosi-fer** [comment]
Aha, to baš nije dobra ideja zato što se onda ovisi o eksternom izvoru, bilo bi bolje baš ih direktno staviti (pa onda nek se na materijalima uređuju ak moraju)

**Comment by InCogNiTo124** [comment]
Problem je sto nije bas dovrseno skroz, tipa fale 2-3 zadace i mozda jos poneki ishod ucenja

**Comment by InCogNiTo124** [comment]
Mozda onda da se doda kad se dovrsi tam pred kraj ljeta? Smor je te docse prevodit u latex/markdown

**Comment by studosi-fer** [comment]
Sve je to okej, dodaj sad što imamo pa se kasnije to lagano ažurira
